import type { Restaurant } from '@shared-types/index';

/** Mock data, Lviv flavor: mostly plausible local names with a few puns. No network, ever. */
const RESTAURANT_NAMES_BY_FOOD_TYPE: Record<string, string[]> = {
  burgers: [
    'Beef & Buns',
    'Meat Hub',
    'Brutal Burger',
    'Файна Булка',
    'Holy Cow',
    'Burger Brothers',
    'Grill Devil',
    'The Patty Field',
    'Smash Lviv',
    'Ratusha Grill',
    'Кручу Верчу',
    'Double Trouble',
    'Mr. Brisket',
    'Котлета Хаус',
    'Бургерна №1',
  ],
  kebabs: [
    'Shawarma King',
    'Kebab Master',
    'Шава на Ринку',
    'Doner Lviv',
    'Sultan Kebab',
    'Шаурма 24/7',
    'Stary Bazar',
    'Kebab i Tochka',
    'Pan Kebab',
    'Шава Шеф',
    'Antalya Grill',
    'Lavash House',
    'Шаурмен',
    'Östan Kebab',
    'Халяль Хаб',
  ],
  salads: [
    'Green Point',
    'Salateira',
    'Fresh Line',
    'Зелена Канапа',
    'Vegano Hooligano',
    'Crisp & Co',
    'Листя',
    'Bowl Room',
    'Detox Lab',
    'Кропива',
    'Avocado Toast',
    'Grass Café',
    'Rukola',
    'Шпинат і Я',
    'Smoothie Bar 7',
  ],
  wok: [
    'Wok This Way',
    'Panda Wok',
    'Noodle Box',
    'Вок на Дровах',
    'Mr. Wok',
    'Asia Express',
    'Локшина',
    'Wok & Roll',
    'Bamboo Bar',
    'Tasty Wok',
    'Дядько Вок',
    'Chop-Chop',
    'Red Dragon',
    'Wok Street',
    'Куряча Лапша',
  ],
  pasta: [
    'Pasta Mia',
    'Felicità',
    'Trattoria 21',
    'Nonna Lviv',
    'Аль Денте',
    'Bella Vista',
    'La Forchetta',
    'Папарделле',
    'Mamma Mia',
    'Basilico',
    'Песто Место',
    'Casa Nostra',
    'Spaghetteria',
    'Олива',
    'Carbonara Bar',
  ],
  sushi: [
    'Sushi Master',
    'Yoko Sushi',
    'Фудзіяма',
    'Rolls Royce',
    'Сакура',
    'Nigiri Lviv',
    'Васабі',
    'Tuna House',
    'Roll Club',
    'Окінава',
    'Суші Хата',
    'Ikura Bar',
    'Maki Maki',
    'Червоний Дракон',
    'Sushi 33',
  ],
  pizza: [
    'Челентано',
    'Pizza Day',
    'Tre Forni',
    'Папа Піца',
    'Diavola',
    'Monaco Pizza',
    'Pizza 360',
    'Дрова & Тісто',
    'Quattro',
    'Vesuvio',
    'La Pizzeria',
    'Піцерія №1',
    'Crusty',
    'Margherita Lviv',
    'Slice of Lviv',
  ],
  ramen: [
    'Ramen Ya',
    'Tokyo Bowl',
    'Рамен Хата',
    'Slurp!',
    'Umami Lab',
    'Naruto Ramen',
    'Бульйон-сан',
    'Menya Lviv',
    'Tonkotsu Bar',
    'Miso Place',
    'Локшина-сан',
    'Oishii',
    'Ramen 24',
    'Душевний Бульйон',
    'Hokkaido',
  ],
  ua: [
    'Криївка',
    'Гасова Лямпа',
    'Пузата Хата',
    'Бачевських',
    'Дім Легенд',
    'Кумпель',
    'Газда',
    'Сало & Co',
    'Вареники Тут',
    'Борщ Бос',
    'Бабусина Хата',
    'Галицька Кухня',
    'Цимес',
    'Вуйко Стефко',
    'Файне Місто',
  ],
  georgian: [
    'Хінкальня',
    'Сакартвело',
    'Тбілісо',
    'Хачапурі & Вино',
    'Mimino',
    'Genatsvale',
    'Suluguni Bar',
    'Пан Хінкалі',
    'Kazbek',
    'Аджика',
    'Мама Манана',
    'Duqani',
    'Batumi Grill',
    'Цинандалі',
    'Хінкалі Хаус',
  ],
};

export const RESTAURANTS: Restaurant[] = Object.entries(RESTAURANT_NAMES_BY_FOOD_TYPE).flatMap(
  ([foodTypeId, names]) =>
    names.map((name, index) => ({
      id: `${foodTypeId}-${index}`,
      name,
      foodTypeId,
    })),
);

export const getRestaurantsByFoodType = (foodTypeId: string): Restaurant[] =>
  RESTAURANTS.filter((restaurant) => restaurant.foodTypeId === foodTypeId);
